name: On-merge workflow

on:
  push:
    branches:
      - master
    paths:
      - "LocalVenue/**"
      - "LocalVenue.Tests/**"
      - ".github/workflows/on-merge-workflow.yml"
      - ".github/workflows/dotnet-build-test-publish.yml"
      - "Shows_Tickets.postman_collection.json"
      - "User_Seats.postman_collection.json"

jobs:
  xunit-test-with-sonarcloud:
    name: Test and Analyze
    uses: ./.github/workflows/dotnet-build-test-publish.yml
    secrets: inherit
    with:
      publish: true

  deploy:
    name: Deploy artifact to Azure
    runs-on: ubuntu-latest
    needs:
      - xunit-test-with-sonarcloud

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "localvenue-webapp-casp0006"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

  postman-tests:
    name: Postman test
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Make directory for newman results
        run: mkdir newman

      - name: Verify deployment
        run: |
          until curl -sSf https://localvenue-webapp-casp0006.azurewebsites.net/ > /dev/null; do
            echo "Waiting for deployment..."
            sleep 10
          done
        shell: bash

      - name: Run Postman tests - Users and Seats
        run: |
          newman run "User_Seats.postman_collection.json" \
            --global-var "BASE_URL=https://localvenue-webapp-casp0006.azurewebsites.net" \
            --global-var "RESPONSE_TIME=3000" \
            --global-var "EMAIL=${{ secrets.ADMIN_EMAIL }}" \
            --global-var "PASSWORD=${{ secrets.ADMIN_PASSWORD }}" \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export testResults/runreport1.html \
            --reporter-htmlextra-darkTheme

      - name: Run Postman tests - Shows and Tickets
        run: |
          newman run "Shows_Tickets.postman_collection.json" \
            --global-var "BASE_URL=https://localvenue-webapp-casp0006.azurewebsites.net" \
            --global-var "RESPONSE_TIME=3000" \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export testResults/runreport2.html \
            --reporter-htmlextra-darkTheme

      - name: Publish Postman results
        uses: actions/upload-artifact@v4
        with:
          name: RunReports
          path: testResults
